# Import Libraries
import numpy as np
import pandas as pd
# Get the data
df = pd.read_csv("C:\\Users\\ziggurat\\Desktop\\python for data science\\hr_dataset_real.csv")
# print(df)
print('---------------------')
print(df.head())
print('---------------------')
print(df.info())
print('---------------------')
print(df.isna().sum())
print('---------------------')
print(df.dtypes)
print('---------------------')
print(df.columns)
print('---------------------')
print(df.describe())
print('---------------------')
print(df["Department"].unique())
print('---------------------')
print(df["Gender"].value_counts())
print('---------------------')
print(df["Gender"].nunique())
print('---------------------')
print(df["Education"].value_counts())
print('---------------------')
print(df["JobRole"].unique())
print('---------------------------------------------------------------------')
print(df.groupby("Department")["MonthlyIncome"].mean())
print('---------------------')
print(df.groupby("JobRole")["MonthlyIncome"].mean())
print('---------------------')
print(df.groupby("Education")["MonthlyIncome"].mean())
print('---------------------')
print(df.groupby("Gender")["Attrition"].value_counts())
print('---------------------')
print(df.groupby("Gender")["Attrition"].value_counts(normalize=True))
print('---------------------')
print(df[df["Attrition"] == "Yes"]["Age"].mean())
print('---------------------')
print(df.groupby("JobSatisfaction")["YearsAtCompany"].mean())
print('---------------------')
corr_incom = np.corrcoef(df["JobSatisfaction"], (df["MonthlyIncome"], df["YearsAtCompany"]))
print(corr_incom)
print('---------------------')
print(df["YearsAtCompany"].corr(df["JobSatisfaction"]))
print('---------------------')
df["Attrition"] = df["Attrition"].replace({"Yes": 1, "No": 0})
print(df)
print('---------------------')
corr_incom = np.corrcoef(df["JobSatisfaction"], (df["MonthlyIncome"], df["Attrition"]))
print(corr_incom)
print('---------------------------------------------------------------------')
import matplotlib.pyplot as plt
dept_count = df["Department"].value_counts()
print(dept_count)
print('---------------------')
plt.figure(figsize=(8,5))
plt.bar(dept_count.index, dept_count.values, color="red")
plt.title('Number of Employee in Department')
plt.xlabel("Department")
plt.ylabel("Number of Employee")
# plt.show()
print('---------------------------------------------------------------------')
import seaborn as sns
sns.countplot(data= df, x = "OverTime", hue="Attrition")
print('---------------------')
sns.countplot(data= df, x= "OverTime", hue="Gender")
print('---------------------')
sns.heatmap(corr_incom, annot=True)
print('---------------------')
corr_incom = pd.DataFrame(corr_incom, ["JobSatisfaction","MonthlyIncome","Attrition"], ["JobSatisfaction","MonthlyIncome","Attrition"])
print(corr_incom)
print('---------------------')
sns.heatmap(corr_incom, annot=True)
plt.title("Corr_incom")
# plt.show()
print('---------------------------------------------------------------------')
sns.boxplot(data= df, x= "JobRole", y="MonthlyIncome", palette="deep")
print('---------------------')
sns .scatterplot(data= df, x="Education", y="MonthlyIncome", hue="Gender")
print('---------------------')
sns.pairplot(df[["MonthlyIncome", "Age", "JobSatisfaction", "YearsAtCompany", "Attrition", "Gender"]] , hue="Gender")
print('---------------------------------------------------------------------')